package com.example.recipe

data class Recipe(
    val id: Int = 0,  // Auto-generated by the database
    val name: String,
    val ingredients: String,
    val notes: String,
    val imageUri: String,  // Use URI instead of blob
    var isFavorite: Boolean
)
